### ISSUE TITLE
provide grafana dashboard

### ISSUE THREAD

**Issue by fafische** [hdecarne-github/fritzbox-telegraf-plugin#4]
On your screenshots, you used grafana to print your charts for the agregated data. Can you please share your grafana dashboard with us?

**Comment by hdecarne** [comment]
Sure, please find below the MESH and the WAN dashboard I use. The former shows the WLAN/MESH related metrics the latter the WAN connection related ones. Just FYI, as the dashboards have been further improved over time, they no longer match the screenshots 100%.

The dashboards are based on Grafana 10.1.0 and use a InfluxDB2 data source (FLUX queries).

[Network_MESH-1693285223809.json.txt](https://github.com/hdecarne-github/fritzbox-telegraf-plugin/files/12460437/Network_MESH-1693285223809.json.txt)
[Network_WAN-1693285245678.json.txt](https://github.com/hdecarne-github/fritzbox-telegraf-plugin/files/12460438/Network_WAN-1693285245678.json.txt)
