### ISSUE TITLE
error parsing fritzbox.conf after container restart

### ISSUE THREAD

**Issue by litronics** [hdecarne-github/fritzbox-telegraf-plugin#5]
Hi,

I am running telegraf in a docker container and install the fritzbox plugin via Dockerfile while building the container.

My problem, and I can reproduce it every time, is that after a container restart the fritzbox.conf has parsing errors.

To reporduce I do the following:
1. empty fritzbox.conf in /etc/telegraf/telegraf.d/
2. restart container (obviously with error messages - see below)
3. copy the fritzbox.conf for /usr/local/bin/telegraf/ to /etc/telegraf/telegraf.d/
4. check logs (fritz.box not found - which is OK)
5. restart container
6. check logs (parsing error in fritzbox.conf)

These are the logs I am referring to (I marked the stages from above):

> 2024-01-16T07:44:21Z I! Starting Telegraf 1.29.1 brought to you by InfluxData the makers of InfluxDB
> 2024-01-16T07:44:21Z I! Available plugins: 241 inputs, 9 aggregators, 30 processors, 24 parsers, 60 outputs, 6 secret-stores
> 2024-01-16T07:44:21Z I! Loaded inputs: execd mem
> 2024-01-16T07:44:21Z I! Loaded aggregators:
> 2024-01-16T07:44:21Z I! Loaded processors:
> 2024-01-16T07:44:21Z I! Loaded secretstores:
> 2024-01-16T07:44:21Z I! Loaded outputs: influxdb
> 2024-01-16T07:44:21Z I! Tags enabled: host=telegraf user=${USER}
> 2024-01-16T07:44:21Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"telegraf", Flush Interval:10s
> 2024-01-16T07:44:21Z I! [inputs.execd] Starting process: /usr/local/bin/telegraf/fritzbox-telegraf-plugin [-config /etc/telegraf/telegraf.d/fritzbox.conf -poll_interval 10s]
>
>--> 2. restarted with empte fritzbox.conf - this error es expectd
>
> 2024-01-16T07:44:21Z E! [inputs.execd] stderr: "Err: nothing to run"
> 2024-01-16T07:44:21Z E! [inputs.execd] Process /usr/local/bin/telegraf/fritzbox-telegraf-plugin exited: exit status 1
> 2024-01-16T07:44:21Z I! [inputs.execd] Restarting in 10s...
> 2024-01-16T07:44:31Z I! [inputs.execd] Starting process: /usr/local/bin/telegraf/fritzbox-telegraf-plugin [-config /etc/telegraf/telegraf.d/fritzbox.conf -poll_interval 10s]
> 2024-01-16T07:44:31Z E! [inputs.execd] stderr: "Err: nothing to run"
> 2024-01-16T07:44:31Z E! [inputs.execd] Process /usr/local/bin/telegraf/fritzbox-telegraf-plugin exited: exit status 1
> 2024-01-16T07:44:31Z I! [inputs.execd] Restarting in 10s...
> 2024-01-16T07:44:41Z I! [inputs.execd] Starting process: /usr/local/bin/telegraf/fritzbox-telegraf-plugin [-config /etc/telegraf/telegraf.d/fritzbox.conf -poll_interval 10s]
> 2024-01-16T07:44:41Z E! [inputs.execd] stderr: "Err: nothing to run"
> 2024-01-16T07:44:41Z E! [inputs.execd] Error in plugin: read |0: file already closed
> 2024-01-16T07:44:41Z E! [inputs.execd] Error in plugin: error reading stderr: read |0: file already closed
> 2024-01-16T07:44:41Z E! [inputs.execd] Process /usr/local/bin/telegraf/fritzbox-telegraf-plugin exited: exit status 1
> 2024-01-16T07:44:41Z I! [inputs.execd] Restarting in 10s...
> 2024-01-16T07:44:51Z I! [inputs.execd] Starting process: /usr/local/bin/telegraf/fritzbox-telegraf-plugin [-config /etc/telegraf/telegraf.d/fritzbox.conf -poll_interval 10s]
> 2024-01-16T07:44:51Z E! [inputs.execd] stderr: "Err: nothing to run"
> 2024-01-16T07:44:51Z E! [inputs.execd] Process /usr/local/bin/telegraf/fritzbox-telegraf-plugin exited: exit status 1
> 2024-01-16T07:44:51Z I! [inputs.execd] Restarting in 10s...
> 2024-01-16T07:45:01Z I! [inputs.execd] Starting process: /usr/local/bin/telegraf/fritzbox-telegraf-plugin [-config /etc/telegraf/telegraf.d/fritzbox.conf -poll_interval 10s]
> 2024-01-16T07:45:01Z E! [inputs.execd] stderr: "Err: nothing to run"
> 2024-01-16T07:45:01Z E! [inputs.execd] Process /usr/local/bin/telegraf/fritzbox-telegraf-plugin exited: exit status 1
> 2024-01-16T07:45:01Z I! [inputs.execd] Restarting in 10s...
> 2024-01-16T07:45:11Z I! [inputs.execd] Starting process: /usr/local/bin/telegraf/fritzbox-telegraf-plugin [-config /etc/telegraf/telegraf.d/fritzbox.conf -poll_interval 10s]
> 2024-01-16T07:45:11Z E! [inputs.execd] stderr: "Err: nothing to run"
> 2024-01-16T07:45:11Z E! [inputs.execd] Process /usr/local/bin/telegraf/fritzbox-telegraf-plugin exited: exit status 1
> 2024-01-16T07:45:11Z I! [inputs.execd] Restarting in 10s...
> 2024-01-16T07:45:21Z I! [inputs.execd] Starting process: /usr/local/bin/telegraf/fritzbox-telegraf-plugin [-config /etc/telegraf/telegraf.d/fritzbox.conf -poll_interval 10s]
> 2024-01-16T07:45:21Z E! [inputs.execd] stderr: "Err: nothing to run"
> 2024-01-16T07:45:21Z E! [inputs.execd] Process /usr/local/bin/telegraf/fritzbox-telegraf-plugin exited: exit status 1
> 2024-01-16T07:45:21Z I! [inputs.execd] Restarting in 10s...
> 2024-01-16T07:45:31Z I! [inputs.execd] Starting process: /usr/local/bin/telegraf/fritzbox-telegraf-plugin [-config /etc/telegraf/telegraf.d/fritzbox.conf -poll_interval 10s]
> 2024-01-16T07:45:31Z E! [inputs.execd] stderr: "Err: nothing to run"
> 2024-01-16T07:45:31Z E! [inputs.execd] Process /usr/local/bin/telegraf/fritzbox-telegraf-plugin exited: exit status 1
> 2024-01-16T07:45:31Z I! [inputs.execd] Restarting in 10s...
> 2024-01-16T07:45:41Z I! [inputs.execd] Starting process: /usr/local/bin/telegraf/fritzbox-telegraf-plugin [-config /etc/telegraf/telegraf.d/fritzbox.conf -poll_interval 10s]
> 2024-01-16T07:45:41Z E! [inputs.execd] stderr: "Err: nothing to run"
> 2024-01-16T07:45:41Z E! [inputs.execd] Process /usr/local/bin/telegraf/fritzbox-telegraf-plugin exited: exit status 1
> 2024-01-16T07:45:41Z I! [inputs.execd] Restarting in 10s...
> 2024-01-16T07:45:51Z I! [inputs.execd] Starting process: /usr/local/bin/telegraf/fritzbox-telegraf-plugin [-config /etc/telegraf/telegraf.d/fritzbox.conf -poll_interval 10s]
> 2024-01-16T07:45:51Z E! [inputs.execd] stderr: "Err: nothing to run"
> 2024-01-16T07:45:51Z E! [inputs.execd] Process /usr/local/bin/telegraf/fritzbox-telegraf-plugin exited: exit status 1
> 2024-01-16T07:45:51Z I! [inputs.execd] Restarting in 10s...
> 2024-01-16T07:46:01Z I! [inputs.execd] Starting process: /usr/local/bin/telegraf/fritzbox-telegraf-plugin [-config /etc/telegraf/telegraf.d/fritzbox.conf -poll_interval 10s]
>
>--> 4. telegraf read the fritzbox.conf and tries to reach out for the fritz.box host (the error is also expected due to DNS configuration
>
> 2024-01-16T07:46:11Z E! [inputs.execd] stderr: "2024/01/16 07:46:11 E! Error in plugin: Get \"http://fritz.box:49000/tr64desc.xml\": dial tcp: lookup fritz.box on 127.0.0.11:53: no such host"
> 2024-01-16T07:46:21Z E! [inputs.execd] stderr: "2024/01/16 07:46:21 E! Error in plugin: Get \"http://fritz.box:49000/tr64desc.xml\": dial tcp: lookup fritz.box on 127.0.0.11:53: no such host"
> 2024-01-16T07:46:31Z E! [inputs.execd] stderr: "2024/01/16 07:46:31 E! Error in plugin: Get \"http://fritz.box:49000/tr64desc.xml\": dial tcp: lookup fritz.box on 127.0.0.11:53: no such host"
> 2024-01-16T07:46:39Z E! [inputs.execd] Error in plugin: read |0: file already closed
> 2024-01-16T07:46:39Z I! [inputs.execd] Process /usr/local/bin/telegraf/fritzbox-telegraf-plugin shut down
> 2024-01-16T07:46:39Z I! [agent] Hang on, flushing any cached metrics before shutdown
> 2024-01-16T07:46:39Z I! [agent] Stopping running outputs
> 2024-01-16T07:46:42Z I! Loading config: /etc/telegraf/telegraf.conf
> 2024-01-16T07:46:42Z I! Loading config: /etc/telegraf/telegraf.d/fritzbox.conf
>
>--> 6. after restart of the container the fritzbox.conf has parsing errors
>
> 2024-01-16T07:46:42Z E! error loading config file /etc/telegraf/telegraf.d/fritzbox.conf: error parsing fritzbox, undefined but requested input: `fritzbox

To be complete with the configuration - this is my Dockerfile:
```ARG TELEGRAF_VERSION

FROM telegraf:${TELEGRAF_VERSION}

RUN apt -y update && apt -y upgrade
RUN apt install -y unzip wget
RUN wget https://github.com/hdecarne-github/fritzbox-telegraf-plugin/releases/download/v0.4.0/fritzbox-linux-amd64-0.4.0.zip
RUN unzip fritzbox-linux-amd64-0.4.0.zip -d /usr/local/bin/telegraf/
```

and this is the part of the compose file used for the container:
``` telegraf:
    #image: "telegraf:latest"
    build:
      context: telegraf/
      args:
        TELEGRAF_VERSION: latest
    hostname: "telegraf"
    container_name: telegraf
    depends_on:
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./telegraf/telegraf.d/:/etc/telegraf/telegraf.d/
    environment:
      -USER: "telegraf"
      -INFLUX_PASSWORD: "ChangeMe!!!"
    networks:
      - influx
 ```

**Comment by hdecarne** [comment]
Hi, I may need some more information.

First note, there are actually two configuration parts required. The actual plugin configuration (normally `fritzbox.conf`) as well as the `inputs.execd` configuration. How did you configure the `inputs.execd` part?
The `fritzbox.conf` file should not be located inside the `telegraf.d` directory. This directory is sourced by Telegraf to build up it's own configuration. While this may not be an issue, I suggest to avoid this to rule out unexpected side effects. You can store the `fritzbox.conf` in `/etc/telegraf` for example. The exact path to this file must be given in the` -conf` parameter of the `inputs.execd `configuration.

A the point the parse error occurs, what is the actual content of `fritzbox.conf` right at this moment?
> --> 6. after restart of the container the fritzbox.conf has parsing errors
> 
> 2024-01-16T07:46:42Z E! error loading config file /etc/telegraf/telegraf.d/fritzbox.conf: error parsing fritzbox, undefined but requested input: `fritzbox

**Comment by litronics** [comment]
Hi, thanks for the quick response!

Here is my Dockerfile which I use to build my telegraf container and install the plugin:

```
ARG TELEGRAF_VERSION

FROM telegraf:${TELEGRAF_VERSION}

RUN apt -y update && apt -y upgrade
RUN apt install -y unzip wget
RUN wget https://github.com/hdecarne-github/fritzbox-telegraf-plugin/releases/download/v0.4.0/fritzbox-linux-amd64-0.4.0.zip
RUN unzip fritzbox-linux-amd64-0.4.0.zip -d /usr/local/bin/telegraf/
```

My telegraf.conf is also straight forward:
```
[global_tags]
  user = "${USER}"

[[inputs.mem]]

[[inputs.execd]]
  command = ["/usr/local/bin/telegraf/fritzbox-telegraf-plugin", "-config", "/etc/telegraf/telegraf.d/fritzbox.conf", "-poll_interval", "10s"]
  signal = "none"

# For InfluxDB 1.x:
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  password = "${INFLUX_PASSWORD}"
```

As you suggested, I moved the `fritzbox.conf` out of `telegraf.d` directory and mounted it directly in `/etc/telegraf/`.

Actually - this was the issue!

It might be a good idea to mention this in the README explicitly.

Thanks for your support!
