### ISSUE TITLE
Not running on arm64

### ISSUE THREAD

**Issue by caveman2003** [hdecarne-github/fritzbox-telegraf-plugin#6]
Hi all, 

i try to run the arm64 plugin on:
ecb8049f37e7:/$ cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.18.4
PRETTY_NAME="Alpine Linux v3.18"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
ecb8049f37e7:/usr/share/grafana$ uname -a
Linux ecb8049f37e7 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 Linux

i get an error that cannot run the binary: Error in program file format...

$ file fritzbox-telegraf-plugin 
fritzbox-telegraf-plugin: Mach-O 64-bit arm64 executable, flags:<|DYLDLINK|PIE>

(this is a docker container running on a PI4). 

do i need to use an debian instead of alpine Linux ?

**Comment by caveman2003** [comment]
please ignore my error ... wrong OS ...

**Comment by hdecarne** [comment]
Yes, the arm64 archive is for Darwin/macOS. However, if you have go installed on your RPI4, the plugin should build without issues on the RPI4 itself.
